FROM nginx:stable-alpine

# Copy custom Nginx configuration file into the container
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Change the path to the SSL certificate and key
COPY certs/fullchain.pem /etc/nginx/ssl/fullchain.pem
COPY certs/privkey.pem /etc/nginx/ssl/privkey.pem

EXPOSE 80 443

